// <auto-generated />
using System;
using HNG14_Backend_Task1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HNG14_Backend_Task2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423103802_grznz")]
    partial class grznz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HNG14_Backend_Task1.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age")
                        .HasAnnotation("Relational:JsonPropertyName", "age");

                    b.Property<string>("AgeGroup")
                        .HasColumnType("text")
                        .HasColumnName("age_group")
                        .HasAnnotation("Relational:JsonPropertyName", "age_group");

                    b.Property<string>("CountryId")
                        .HasMaxLength(2)
                        .HasColumnType("varchar")
                        .HasColumnName("country_id")
                        .HasAnnotation("Relational:JsonPropertyName", "country_id");

                    b.Property<string>("CountryName")
                        .HasColumnType("varchar")
                        .HasColumnName("country_name")
                        .HasAnnotation("Relational:JsonPropertyName", "country_name");

                    b.Property<double?>("CountryProbability")
                        .HasColumnType("double precision")
                        .HasColumnName("country_probability")
                        .HasAnnotation("Relational:JsonPropertyName", "country_probability");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender")
                        .HasAnnotation("Relational:JsonPropertyName", "gender");

                    b.Property<float?>("GenderProbability")
                        .HasColumnType("real")
                        .HasColumnName("gender_probability")
                        .HasAnnotation("Relational:JsonPropertyName", "gender_probability");

                    b.Property<string>("Name")
                        .HasColumnType("varchar")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
